<a href="https://www.kaggle.com/code/sreenijadreddy/cognizance-task-1-question-3-pandas?scriptVersionId=128532991" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
l = [10,20,30,40,50]
d1 = {"a": 10, "b": 20, "c": 30, "d": 40, "e": 50}
print("List l:",l,"\n")
print("Dictionary d1:",d1,"\n")
print("CONVERSION OF LIST INTO SERIES\n")
series_list = pd.Series(l)
print("Series from list l:")
print(series_list,"\n")

print("CONVERT DICTIONARY TO A SERIES\n")
series_dictionary = pd.Series(d1)
print("Series from dictionary d1:")
print(series_dictionary,"\n")

print("ADDITION OF TWO SERIES\n")
print("Series 1:\nIndia 1\nSrilanka 2\nBangladesh 3\nRussia 4\nEngland 5\n")
print("Series 2:\nIndia 6\nSrilanka 7\nBangladesh 8\nRussia 9\nEngland 10\n")
series1 = pd.Series([1, 2, 3, 4, 5], index=['India', 'Srilanka', 'Bangladesh', 'Russia', 'England'])
series2 = pd.Series([6, 7, 8, 9, 10], index=['India', 'Srilanka', 'Bangladesh', 'Russia', 'England'])
added_series = series1 + series2
print("Added Series:")
print(added_series,"\n")

print("CREATION OF DATA FRAME\n")
np.random.seed(0)
data = np.random.randint(0, 100, (5, 4))
data_frame = pd.DataFrame(data, columns=['W', 'X', 'Y', 'Z'], index=['A', 'B', 'C', 'D', 'E'])
print("DataFrame:")
print(data_frame,"\n")

print("DATAFRAME INTO EXCEL FILE\n")
data_frame.to_excel('dataframe.xlsx', index=True)
print('/kaggle/working/dataframe.xlsx')
print("DataFrame written to 'dataframe.xlsx' file.\n")

print("ACCESS A COLUMN AND A ROW OF THE DATAFRAME\n")
column_X = data_frame['X']
row_A = data_frame.loc['A']
print("Accessed Column X:")
print(column_X)
print("\nAccessed Row A:")
print(row_A,"\n")

print("ACCESS DATA WITH INDEX VALUES OF ROW A\n")
data_loc_A = data_frame.loc['A']
data_iloc_A = data_frame.iloc[0]
print("Data using loc for row A:")
print(data_loc_A)
print("\nData using iloc for row A:")
print(data_iloc_A,"\n")

print("SELECTION OF A SUBSET OF DATA\n")
subset_loc = data_frame.loc[['A', 'E'], ['W', 'Z']]
print("Subset of data using loc for rows A and E, and columns W and Z:")
print(subset_loc,"\n")

print("DROP A ROW")
df_dropped = data_frame.drop('A')
print("\nDataFrame after dropping the first row:")
print(df_dropped,"\n")

List l: [10, 20, 30, 40, 50]

Dictionary d1: {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

CONVERSION OF LIST INTO SERIES

Series from list l:
0    10
1    20
2    30
3    40
4    50
dtype: int64

CONVERT DICTIONARY TO A SERIES

Series from dictionary d1:
a    10
b    20
c    30
d    40
e    50
dtype: int64

ADDITION OF TWO SERIES

Series 1:
India 1
Srilanka 2
Bangladesh 3
Russia 4
England 5

Series 2:
India 6
Srilanka 7
Bangladesh 8
Russia 9
England 10

Added Series:
India          7
Srilanka       9
Bangladesh    11
Russia        13
England       15
dtype: int64

CREATION OF DATA FRAME

DataFrame:
    W   X   Y   Z
A  44  47  64  67
B  67   9  83  21
C  36  87  70  88
D  88  12  58  65
E  39  87  46  88

DATAFRAME INTO EXCEL FILE

/kaggle/working/dataframe.xlsx
DataFrame written to 'dataframe.xlsx' file.

ACCESS A COLUMN AND A ROW OF THE DATAFRAME

Accessed Column X:
A    47
B     9
C    87
D    12
E    87
Name: X, dtype: int64

Accessed Row A:
W    44
X    47
Y    64
Z    67
Name: A, dtype: int64

ACCESS DATA WITH INDEX VALUES OF ROW A

Data using loc for row A:
W    44
X    47
Y    64
Z    67
Name: A, dtype: int64

Data using iloc for row A:
W    44
X    47
Y    64
Z    67
Name: A, dtype: int64

SELECTION OF A SUBSET OF DATA

Subset of data using loc for rows A and E, and columns W and Z:
    W   Z
A  44  67
E  39  88

DROP A ROW

DataFrame after dropping the first row:
    W   X   Y   Z
B  67   9  83  21
C  36  87  70  88
D  88  12  58  65
E  39  87  46  88